"""Add terms_accepted to Users

Revision ID: c7f8e9a1b2d3
Revises: 67ebab6de598
Create Date: 2025-12-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7f8e9a1b2d3"
down_revision = "67ebab6de598"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("terms_accepted", sa.Boolean(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "terms_accepted")
    # ### end Alembic commands ###
